### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by bfred-it** [dzhavat/potential-changes-for-github#15]
I don't see any button anymore on Chrome. Example URLs:

https://github.com/bfred-it/insert-text-textarea/blob/master/index.ts
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts

**Comment by dzhavat** [comment]
Thank you for reporting it!

It looks like GitHub now outputs different classes so the code below returns immediately (because `fileActions` is `null`).

https://github.com/dzhavat/potential-changes-for-github/blob/b87ffc7a9bf5660a92f036f2cb6a58fcd48b5355/source/content.js#L13-L17

I'm gonna try fixing it in the upcoming days and will push an update to the extension.
